### ISSUE TITLE
Remove '>' from bash code blocks.

### ISSUE THREAD

**Issue by cameronelliott** [assist-project/dtls-fuzzer#18]
In the readme every shell line has a '> ' before the command.
ie:

    > sudo apt-get install openjdk-8-jdk

The greater sign at the start if the line is not needed for this command to execute under bash.
But it does cause issues for other shell users.

For bash, normally, greater than indicates stdout should be redirected.  [reference link](https://www.gnu.org/software/bash/manual/bash.html#Redirecting-Output)
But typically '>' is followed by a file name or other syntax.
But followed by a space character, it seems bash ignores this stdout redirect.

But it causes problems for users of other shells (like the fish shell):
<img width="430" alt="image" src="https://user-images.githubusercontent.com/868689/202876468-a04f6bae-ef2e-4f3f-a58b-93679a8a85fe.png">

The greater than signs do add a nice visual highlight, but might not be necessary as the README page on github seems to be pretty clear that the block is a "click-copy-paste".
See this screenshot inside the border.

<table><tr><td>
    <img width="834" alt="image" src="https://user-images.githubusercontent.com/868689/202876539-245ae1ff-3c13-4b6f-85d4-789afd6829ad.png">
</td></tr></table>

If the greater sign was removed, would users be less clear about the purpose of the code block??
I suspect probably not for most.

As another point in support of removing the '> ' chars, please see this openjdk building page:
[This open jdk build directions don't contain '>' chars](https://github.com/openjdk/jdk/blob/master/doc/building.md)

**_I suggest considering removing the '> ' character from the start of the shell commands in the README_**

If removing the pain for non-bash shell users is deemed useful,  then I could submit a PR.

**Comment by kostis** [comment]
Thanks for your interest in DTLS-Fuzzer and for this suggestion.
It's a bit of a detail, but it does allow for easier copy-paste of the instructions, so it has been adopted.
I am closing this issue.

**Comment by cameronelliott** [comment]
Thank you
