### ISSUE TITLE
install.sh not working on macOS

### ISSUE THREAD

**Issue by Giocorna1** [assist-project/dtls-fuzzer#84]
running install.sh returns COMPILATION WARNING: system modules path not set in conjunction with -source 11
Then
COMPILATION ERROR : (with 100 errors 'does not exists)like:
/Users/giorgiocorna/dtls-fuzzer/src/main/java/se/uu/it/dtlsfuzzer/sut/io/ClientHelloRenegotiationInput.java:[3,33] package javax.xml.bind.annotation does not exist

This can't let me install dtls-fuzzer.
All requirements (Java11, Maven...) are satisfied.

**Comment by pfg666** [comment]
Hi  @Giocorna1 ,

Unfortunately, I am don't have a computer running macOS to reproduce the problem. It would help if you told me which version of DTLS-Fuzzer you are running. The [USENIX release](https://github.com/assist-project/dtls-fuzzer/releases) requires Java 8 (and will not work with a newer version of Java). The latest in the master branch should work on Java 11. Did you try:

``` 
> export JAVA_HOME=`/path/to/java11_home`
> bash install.sh 
```

**Comment by kostis** [comment]
None of us has access to a Mac to test or reproduce this, but perhaps you may have better luck with cloning the current `master` branch which AFAIK does not, directly at least, need / use `javax.xml.bind.annotation`.

**Comment by Giocorna1** [comment]
tried not to clone the repository but downloaded it as zip file and it worked. So it's a problem with git-clone. Btw now i have problems with setup_sut.sh openssl-1.1.1b. It gives me this: setup_sut.sh: line 235: wget: command not found
Failed to load the archive at the URL: https://www.openssl.org/source/old/1.1.1/openssl-1.1.1b.tar.gz
rm: /tmp/dtls-fuzzer-root/openssl-1.1.1b.tar.gz: No such file or directory

**Comment by kostis** [comment]
`wget` is a standard (and pretty well-known) GNU command to download/get some file from the Web.  I am sure it exists on MacOS in some form.

**Comment by Giocorna1** [comment]
Just figured it out after commenting. Had to install wget manually. Thanks for fast reply
